// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Launch', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Launch', async function() {
    await driver.get("http://sudoko.azurewebsites.net")
    await driver.manage().window().setRect(1366, 728)
    await driver.findElement(By.linkText("New")).click()
  })
})
